### ISSUE TITLE
CMake error on macOS due to missing Welcome.rtf

### ISSUE THREAD

**Issue by rickertm** [coin3d/simage#35]
In release 1.8.0 and on the current master with enabled `SIMAGE_USE_CPACK` option, CMake cannot complete the configuration due to a missing `Welcome.rtf`. See cpack.d [line 122](https://github.com/coin3d/cpack.d/blob/aa85910bee708278b3e26df62faa8621ef7cc4c4/CMakeLists.txt#L122) for the relevant code.

```
CMake Error: File /Users/test/workspace/simage/packaging/macosx/Welcome.rtf does not exist.
CMake Error at cpack.d/CMakeLists.txt:122 (configure_file):
  configure_file Problem configuring file


-- Configuring incomplete, errors occurred!
```

**Comment by veelo** [comment]
@VolkerEnderlein the line in question is yours, from 12 months ago (or is that due to the hg=>git conversion?). Or maybe something changed on the cpack side of things, @ggabbiani? Anyway, I'm out of my league here...

**Comment by ggabbiani** [comment]
cpack.d is missing the support to hg, I have already fixed locally some time ago but I had not time to push the changes. I guess that that the log should anyway report a warn about 'Mercurial found'. I can take care of both.

Giampiero

**Comment by ggabbiani** [comment]
Hi Markus,

just updated cpack.d with the proper cmake code for correct build with the new git repo. 

I also added to simage the missing Welcome.rtf file.

Unfortunately I don't have a Mac for checking these changes, and after a look to the DMGSetup.scpt.in I suspect that at least another tiff file is missing in simage/packaging/macosx.

@rickertm could you check now?

@VolkerEnderlein please Volker in case anything else is missing for Mac could you check end eventually fix?

In the meanwhile I will propagate the changes in the cpack.d to all the other client projects.

Regards
Giampiero

**Comment by rickertm** [comment]
Thank you for adding the file. I can confirm that the CMake configure step now works on macOS with enabled `SIMAGE_USE_CPACK` option.

It would be nice if you can tag a new version with these changes.

**Comment by VolkerEnderlein** [comment]
@veelo Unfortunately I am not able to react properly, because I am on holidays. Will check on saturday when I'm back. Cheers, Volker

Am 11.02.2020 00:07 schrieb Bastiaan Veelo <notifications@github.com>:

@VolkerEnderlein<https://github.com/VolkerEnderlein> the line in question is yours, from 12 months ago (or is that due to the hg=>git conversion?). Or maybe something changed on the cpack side of things, @ggabbiani<https://github.com/ggabbiani>? Anyway, I'm out of my league here...
