### ISSUE TITLE
Input on some intentions by devs wanted

### ISSUE THREAD

**Issue by waebbl** [coin3d/simage#46]
Hello, on Gentoo Linux we have the notion, for users to decide whether to build packages with enabled / disabled features, where applicable, through so called USE flags.
The current Gentoo package build script for version 1.8.0 has USE flags to support gif, jpeg, png and tiff file formats, i.e. to enable or disable support for those formats. A doc comment in the `simage.h` file on function `simage_check_save_supported` states, that gif, jpeg, png, tif and rgb formats are built-in savers, thus I assume, they should be supported by default.
Additionally the cmake files doesn't use any `option` cmake commands to clearly state these features as optional or not. On the other side, the `find_package` commands for those file formats don't have a `REQUIRED` flag set, which indicates, they might be optional.
My question now is, what's the intention of the simage dev team on the requirements of those file formats?

For a more in-depth discussion on Gentoo regarding this topic, please see https://github.com/waebbl/waebbl-gentoo/issues/274#issuecomment-751221723

TIA

**Comment by VolkerEnderlein** [comment]
I cannot speak for the original devs, as they left long ago and the project was maintained since then on a minimum base. But this seems to have been missed when the `CMakeLists.txt` was initially created from the configure script. According to `configure.ac` the default values for `--with-gif`, `--with-jpeg`, `--with-png`, and `--with-tiff` are only set to `true` if the platform does not request support for QuickTime, CGImage, or GDI+, so that the libraries are requested when simage is built. As I'm just working on releasing 1.8.1 version this will be corrected there too. Thanks for notifying us about the issue.

**Comment by waebbl** [comment]
Thanks @VolkerEnderlein for your reply. This is true for the CMakeLists.txt file as well. The packages are only searched for, when neither QuickTime, CGImage nor GDI+ is supported, which is always true on Linux platforms.

**Comment by VolkerEnderlein** [comment]
Thanks @waebbl . This is exactly what I meant. If the autotools script had the options, they are required in the CMakeLists.txt script too.
I just committed the fix f8fa2027019b93d76f8a846a6dfbd5e8363e0f14 for those missing options and for the broken pkg-config file simage.pc . Can you test it and report back whether it solves the issue(s) you experienced? Cheers

**Comment by waebbl** [comment]
@VolkerEnderlein At a quick look this looks good and definitely answer our question whether the support for this file formats is optional.
I'm setting up a live ebuild and do some extended testing on the git master sources and report back on the experiences.

**Comment by waebbl** [comment]
@VolkerEnderlein The changes work very well. I had only one small issue. When building with gif support, the giflib directory is included in the `INCLUDE_DEPENDENCIES` list, which get's added to the pkg-config file. As this directory is inside a sandbox during build, the directory is no longer available once the package is installed. I solved it, by adding this directory so a `INCLUDE_DEPENDENCIES_PRIVATE` list, and included the list in the `target_include_directories` command. See the attached patch on this approach.
Thanks for your great work!

[simage-9999-0002-CMakeLists.txt-Fix-giflib-include-directories.patch.txt](https://github.com/coin3d/simage/files/5752073/simage-9999-0002-CMakeLists.txt-Fix-giflib-include-directories.patch.txt)

**Comment by VolkerEnderlein** [comment]
Thanks @waebbl , I just fixed that issue. Another question on my side arises. Is it ok to place the runtime dependencies in `Requires.private` and only add the compile time dependencies in `Requires` ? Somehow I read the docs over and over but didn't find finally the answer to this.

**Comment by waebbl** [comment]
@VolkerEnderlein To my understanding from the pkg-config info file, `Requires` is used for dynamically linked libraries, whereas `Requires.private` is used for statically linked libraries. So from this, the runtime dependencies should be placed into `Requires`. As to what exactly needs to go into `Requires.private` in this case, I'm not sure. I assume, all libraries which need to available as a static library, when simage is built with support for static libraries.
As an example, I looked at the pkgconfig file of glib-2. The `Requires.private` field contains libpcre, while the `Requires` field is empty. The build script passes the `static-libs` USE flag to the libpcre package, to ensure this package is build with static-libs as well, if glib's static libraries are built. If glib is build without static libs, this USE flag is not enforced on libpcre and libpcre can be built with or without static libs. But even then, the pkg-config file still has the `Requires.private` field for libpcre. This can be an issue with the build system not reflecting this decision properly, or intentional, I don't know. From this, I assume, that all required libs needed for static linking are listed there. Due to how the dynamic linker is working on Linux, the `Requires` field could be empty, as the linker is resolving those dependencies automatically.
One more point on this regarding the quantize support for giflib. If simage is compiled with a new enough giflib to support quantization, this should, from my understanding, be reflected in the `Requires{,.private}` flag as well, thus using a comparison operator, to ensure the installed giflib is able to handle this, and to give a hint to the user, if they want to downgrade their installed giflib.

**Comment by VolkerEnderlein** [comment]
Thanks @waebbl for the explanations. Meanwhile I also searched for further information on the issue and stumbled across the following [website](https://autotools.io/pkgconfig/dependencies.html#pkgconfig.static-link) which exactly explains how to fill those fields. If the shared library **exposes** types and classes from the linked shared libraries and a `.pc` file for the dependency exist you need to add the `.pc` file name to the `Requires` section. If no `.pc` file exists for the dependency you need to add it to the `Libs` section. If types and classes from the dependencies are used only internally you need to add them to the `Requires.private` or `Libs.private` sections to make sure the linking to the static library can be performed successfully.

**Comment by VolkerEnderlein** [comment]
@waebbl patch version v1.8.1 of simage has been released and should address the issues. Please report back whether further action is needed or the issue can be closed.

**Comment by waebbl** [comment]
@VolkerEnderlein Thanks for the great work. I'm gonna test it.

**Comment by waebbl** [comment]
@VolkerEnderlein The issue can be closed. The build works fine and as expected as far as I can see.
