### ISSUE TITLE
Error when reading images with very small file size

### ISSUE THREAD

**Issue by rickertm** [coin3d/simage#57]
The function `find_loader()` called by `simage_check_supported()` returns `NULL` when called on images with a very small file size (<256 bytes). Example images for this are the [test.gif](https://github.com/Homebrew/brew/blob/a8bb0d6581ccc75c109552e2d02b3268368aa6af/Library/Homebrew/test/support/fixtures/test.gif) (35 bytes) and [test.png](https://github.com/Homebrew/brew/blob/a8bb0d6581ccc75c109552e2d02b3268368aa6af/Library/Homebrew/test/support/fixtures/test.png) (82 bytes) files included in Homebrew.

When using the `loaders` test, this results in a failed test and the message "x is not in a supported format":
```console
$ loaders test.gif
``test.gif'' is not in a supported format
$ loaders test.png
``test.png'' is not in a supported format
```

This is due to the `feof(fp)` call in `simage.c`. As the `identity_func()` gets the `readlen` value as parameter, this can likely be omitted.
https://github.com/coin3d/simage/blob/3940692136e02b9e62b3061cf72f053827b5494e/src/simage.c#L159-L160

**Comment by VolkerEnderlein** [comment]
Thanks for the thorough bug report. I just committed the change and added  the two small files to the tests. I'll publish a 1.8.3 release later today.

**Comment by rickertm** [comment]
Thank you for the quick fix and the new release.
